iptables_pkgs:
  - iptables-services
  - iptables-utils
iptables_service: iptables
iptables_config: '/etc/sysconfig/iptables'
iptables_config: '/etc/sysconfig/iptables_audit'
iptables_config: '/etc/sysconfig/iptables_backup'
iptables_show_rules: true
