- name: Get server IP
  command: hostname -I
  register: ip_output

- name: Extract first IP address
  set_fact:
    server_ip: "{{ ip_output.stdout.split()[0] }}"

- name: Check file
  stat:
    path: "{{ iptables_config }}"
  register: file_data

- name: copy file
  shell: cp /home/veerender/Documents/POC/test.txt /home/veerender/Documents/POC/audittest.txt
  when: not file_data.stat.exists

- name: Run diff for left side (lines in iptables not in auditiptables)
  shell: diff --old-line-format='%L' --new-line-format='' --unchanged-line-format='' {{ iptables_config }}  {{ iptables_audit }}
  register: left_diff
  failed_when: left_diff.rc not in [0, 1]
  ignore_errors: true

- name: Run diff for right side (lines in auditiptables not in iptables)
  shell: diff --old-line-format='' --new-line-format='%L' --unchanged-line-format=''  {{ iptables_config }}  {{ iptables_audit }}
  register: right_diff
  failed_when: right_diff.rc not in [0, 1]
  ignore_errors: true

- name: Prepare CSV row with Server IP, Original, Audit
  set_fact:
    csv_line: >-
      "{{ server_ip }}","{{ left_diff.stdout | replace('\"', '\"\"') | replace('\n', '\\n') }}","{{ right_diff.stdout | replace('\"', '\"\"') | replace('\n', '\\n') }}"
  delegate_to: localhost

- name: Create CSV file with header if it doesn't exist
  shell: |
    FILE="$(pwd)/iptables_diff.csv"
    [ -f "$FILE" ] || echo '"Server IP","Original","Audit"' > "$FILE"
  delegate_to: localhost
  run_once: true

- name: Append CSV row to file
  lineinfile:
    path: /home/veerender/Documents/POC/iptables_diff.csv
    line: "{{ csv_line }}"
    create: yes
    insertafter: EOF
  delegate_to: localhost
